# Generated by Django 6.1.1 on 2026-09-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='address',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='code',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='is_active',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='location_address',
            field=models.CharField(blank=True, default='', help_text='Physical location e.g., Industrial Zone A, Algiers', max_length=255),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='manager_name',
            field=models.CharField(blank=True, help_text='Manager displayed under name, e.g., Ahmed Benali', max_length=100),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Aisle/Rack/Bin code within warehouse e.g., A-01, A-02', max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
