# Generated by Django 6.1.1 on 2026-09-26 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_remove_warehouse_address_remove_warehouse_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Storage bin/aisle inside warehouse, e.g., A-01, A-02', max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location_address',
            field=models.CharField(blank=True, default='', help_text='Specific street or industrial zone address', max_length=255),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='manager_name',
            field=models.CharField(blank=True, help_text='Manager name e.g., Ahmed Benali', max_length=100),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Select region/city to filter warehouses', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='warehouse.region'),
        ),
    ]
