# Generated by Django 6.1.1 on 2026-09-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory Items'},
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=100, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price (₹)'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='product_name',
            field=models.CharField(default='Unnamed Product', max_length=255, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sku',
            field=models.CharField(default='TTU', max_length=100, unique=True, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(blank=True, default='pcs', help_text='e.g. pcs, bags, roll, pairs', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='warehouse',
            field=models.CharField(blank=True, default='Main Warehouse', max_length=100, null=True, verbose_name='Warehouse'),
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='reserved_quantity',
        ),
    ]
