# Generated by Django 6.1.1 on 2026-09-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_available',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_stock_threshold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, help_text='Prefix used in SKUs, e.g., RAW, FUR, GRO', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='current_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_threshold',
            field=models.IntegerField(default=10, help_text='Stock level at or below which low stock alert is triggered'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilograms'), ('l', 'Liters'), ('box', 'Boxes'), ('m', 'Meters')], default='pcs', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_quantity',
            field=models.IntegerField(default=50, help_text='Suggested quantity to order when replenishing stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='e.g. RAW-SR-001, FUR-CH-042', max_length=100, unique=True),
        ),
    ]
